### ISSUE TITLE
HOPR Node Network Data Visualisation

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hoprd-legacy#3]
- [ ] In short, we'll looking to get some information from running `hopr-node`'s and output them as part of `hopr-admin`. The [discussion](https://discuss.libp2p.io/t/logging-capabilities-and-parsing-engines-for-libp2p-nodes/607) with the `libp2p` team shows that they are moving to an instrospection data structure, so we can use something like Prometheus instead of `debug` to try and tail these logs for data processing.

Something also for @SCBuergel and @nionis

**Comment by peterbraden** [comment]
Bookmarking these for reference:
- https://github.com/yzalis/Identicon
- https://github.com/danfinlay/jazzicon
